dbfilename redis_cache.rdb
dir /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/pids
pidfile /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13000
maxmemory 755mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/redis_cache.acl
