dbfilename redis_queue.rdb
dir /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/pids
pidfile /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/muhammad-shahwaiz-ali/data_drive/app_omc/backend_omc_app/frappe-bench/config/redis_queue.acl
