#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"; source "$SCRIPT_DIR/lib/common.sh"
ACTION="${1:-status}"; [[ $# -gt 0 ]] && shift || true; SITE=""; NO_BACKUP=0
while (($#)); do case "$1" in --site) SITE="$2"; shift 2;; --no-backup) NO_BACKUP=1; shift;; *) die "unknown option: $1";; esac; done
setup_log "site-$ACTION"; need_sudo; load_config
BENCH_USER="${BENCH_USER:-$USER}"; BENCH_DIR="${BENCH_DIR:-$BACKEND_DIR/frappe-bench}"; APP_SOURCE_DIR="${APP_SOURCE_DIR:-$BACKEND_DIR/apps/omc_app}"; SITE="${SITE:-${SITE_NAME:-}}"
[[ -d "$BENCH_DIR/apps/frappe" ]] || die "Bench missing: $BENCH_DIR"; [[ -n "$SITE" ]] || die 'provide --site or SITE_NAME'
new_site(){ site_exists "$SITE" && die "site already exists: $SITE"; ensure_db_admin; ensure_custom_app; local admin="$(random_secret)"; bench_cmd bench new-site "$SITE" --admin-password "$admin" --db-root-username frappe_admin --db-root-password "$FRAPPE_DB_ADMIN_PASSWORD" --mariadb-user-host-login-scope localhost; bench_cmd bench --site "$SITE" install-app omc_app; post_site; info 'Administrator password was generated; store it now from this terminal session only:'; printf '%s\n' "$admin"; }
post_site(){ ensure_custom_app; bench_cmd bench --site "$SITE" migrate; bench_cmd bench --site "$SITE" clear-cache; bench_cmd bench --site "$SITE" enable-scheduler; bench_cmd bench use "$SITE"; bench_cmd bench build; setup_production; }
setup_production(){ bench_cmd bench setup supervisor; bench_cmd bench setup nginx; "${SUDO[@]}" ln -sfn "$BENCH_DIR/config/supervisor.conf" /etc/supervisor/conf.d/frappe-bench.conf; "${SUDO[@]}" ln -sfn "$BENCH_DIR/config/nginx.conf" /etc/nginx/conf.d/frappe-bench.conf; "${SUDO[@]}" rm -f /etc/nginx/sites-enabled/default; "${SUDO[@]}" sed -i 's#access_log /var/log/nginx/access.log main;#access_log /var/log/nginx/access.log;#g' "$BENCH_DIR/config/nginx.conf"; "${SUDO[@]}" supervisorctl reread; "${SUDO[@]}" supervisorctl update; "${SUDO[@]}" supervisorctl restart all; "${SUDO[@]}" nginx -t; "${SUDO[@]}" systemctl reload nginx; }
cleanup(){ site_exists "$SITE" || warn 'site directory already absent'; read -r -p "Type CLEANUP $SITE to continue: " x; [[ "$x" == "CLEANUP $SITE" ]] || die cancelled; ((NO_BACKUP)) || bench_cmd bench --site "$SITE" backup --with-files; ensure_db_admin; bench_cmd bench drop-site "$SITE" --force --db-root-username frappe_admin --db-root-password "$FRAPPE_DB_ADMIN_PASSWORD" || true; rm -rf "$BENCH_DIR/sites/$SITE"; }
case "$ACTION" in new) new_site;; install-app) ensure_custom_app; bench_cmd bench --site "$SITE" install-app omc_app;; migrate) ensure_custom_app; bench_cmd bench --site "$SITE" migrate;; drop|cleanup) cleanup;; status) bench_cmd bench --site "$SITE" list-apps || true; "${SUDO[@]}" supervisorctl status || true;; production) setup_production;; *) die 'actions: new|install-app|migrate|drop|cleanup|status|production';; esac
