#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"; source "$SCRIPT_DIR/lib/common.sh"
CMD="${1:-help}"; [[ $# -gt 0 ]] && shift || true; SITE=""; ALL=0; TARGET=""
while (($#)); do case "$1" in --site) SITE="$2"; shift 2;; --all-sites) ALL=1; shift;; --target) TARGET="$2"; shift 2;; *) die "Unknown option $1";; esac; done
setup_log "deploy-$CMD"; load_mode_config production; BENCH_DIR="${BENCH_DIR:-/home/frappe/frappe-bench}"; SITE="${SITE:-${SITE_NAME:-}}"; BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-14}"; MAINT=0
[[ "$CMD" == help ]] || [[ -d "$BENCH_DIR/apps/frappe" ]] || die "Bench missing: $BENCH_DIR"
maintenance_off(){ if ((MAINT)) && [[ -n "$SITE" ]]; then bench_cmd bench --site "$SITE" set-maintenance-mode off || true; fi; }
trap maintenance_off EXIT
sites(){ if ((ALL)); then find "$BENCH_DIR/sites" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep -v '^assets$'; else [[ -n "$SITE" ]] || die 'Use --site SITE or --all-sites'; printf '%s\n' "$SITE"; fi; }
backup_one(){ local s="$1"; bench_cmd bench --site "$s" backup --with-files; mkdir -p "$BACKUP_DIR/$s"; find "$BENCH_DIR/sites/$s/private/backups" -type f -mmin -10 -exec cp -n {} "$BACKUP_DIR/$s/" \; || true; cleanup_old_backups; }
setup_prod(){ [[ -n "$SITE" ]] || die '--site required'; site_exists "$SITE" || die 'Site does not exist'; sudo bench setup production "${BENCH_USER:-frappe}"; bench_cmd bench --site "$SITE" set-config developer_mode 0; bench_cmd bench --site "$SITE" enable-scheduler; sudo nginx -t; sudo systemctl enable --now nginx supervisor; if confirm 'Enable HTTPS with Certbot?' Y; then [[ -n "${SSL_EMAIL:-}" ]] || prompt SSL_EMAIL 'Email for SSL'; sudo certbot --nginx -d "$SITE" --non-interactive --agree-tos -m "$SSL_EMAIL" --redirect; fi; ok 'production setup complete'; }
update_code(){ local app="${APP_NAME:-omc_app}" dir="$BENCH_DIR/apps/$app"; [[ -d "$dir/.git" ]] || { warn 'app is not a git checkout; skipping git pull'; return; }; git -C "$dir" fetch --prune origin; git -C "$dir" checkout "${APP_BRANCH:-main}"; git -C "$dir" pull --ff-only origin "${APP_BRANCH:-main}"; }
deploy_one(){ local s="$1"; SITE="$s"; backup_one "$s"; bench_cmd bench --site "$s" set-maintenance-mode on; MAINT=1; bench_cmd bench setup requirements; bench_cmd bench build; bench_cmd bench --site "$s" migrate; bench_cmd bench --site "$s" clear-cache; bench_cmd bench --site "$s" clear-website-cache; bench_cmd bench restart; bench_cmd bench --site "$s" set-maintenance-mode off; MAINT=0; curl -fsS --max-time 20 "https://$s/api/method/ping" >/dev/null || die "Health check failed for $s"; ok "deployment healthy: $s"; }
rollback_code(){ [[ -n "$TARGET" ]] || die 'Use --target COMMIT'; local app="${APP_NAME:-omc_app}" dir="$BENCH_DIR/apps/$app"; [[ -d "$dir/.git" ]] || die 'App is not a git checkout'; git -C "$dir" cat-file -e "$TARGET^{commit}" || die 'Unknown commit'; git -C "$dir" checkout --detach "$TARGET"; for s in $(sites); do deploy_one "$s"; done; }
restore_db(){ [[ -n "$SITE" ]] || die '--site required'; local backup; prompt backup 'Backup SQL/SQL.GZ path'; [[ -f "$backup" ]] || die 'Backup not found'; read -r -p "Type RESTORE $SITE to continue: " x; [[ "$x" == "RESTORE $SITE" ]] || die 'Cancelled'; bench_cmd bench --site "$SITE" restore "$backup"; bench_cmd bench --site "$SITE" migrate; bench_cmd bench restart; }
status(){ sudo systemctl --no-pager --full status nginx supervisor mariadb redis-server || true; bench_cmd bench doctor || true; }
logs(){ tail -n 200 -f "$BENCH_DIR/logs/web.error.log" "$BENCH_DIR/logs/worker.error.log"; }
case "$CMD" in setup) setup_prod;; deploy) for s in $(sites); do deploy_one "$s"; done;; update) update_code; for s in $(sites); do deploy_one "$s"; done;; rollback) rollback_code;; backup) for s in $(sites); do backup_one "$s"; done;; restore) restore_db;; status) status;; logs) logs;; ssl) [[ -n "$SITE" ]] || die '--site required'; sudo certbot --nginx -d "$SITE";; help) echo 'Usage: ./deploy.sh setup|deploy|update|rollback|backup|restore|status|logs|ssl [--site SITE|--all-sites] [--target COMMIT]';; *) die "Unknown command: $CMD";; esac
