#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"; source "$SCRIPT_DIR/lib/common.sh"
CMD="${1:-menu}"; [[ $# -gt 0 ]] && shift || true; MODE="${MODE:-local}"; SITE=""
while (($#)); do case "$1" in --mode) MODE="$2"; shift 2;; --site) SITE="$2"; shift 2;; *) die "Unknown option $1";; esac; done
setup_log "site-$CMD"; load_mode_config "$MODE"; BENCH_DIR="${BENCH_DIR:-$HOME/frappe-bench}"; APP_NAME="${APP_NAME:-omc_app}"; APP_BRANCH="${APP_BRANCH:-main}"; APP_SOURCE_TYPE="${APP_SOURCE_TYPE:-monorepo}"; APP_REPO_URL="${APP_REPO_URL:-https://github.com/mshahwaiz-ali/omc_app.git}"; APP_SUBDIRECTORY="${APP_SUBDIRECTORY:-backend_omc_app/frappe-bench/apps/omc_app}"
[[ -d "$BENCH_DIR/apps/frappe" ]] || die "Bench is not initialized: $BENCH_DIR"
resolve_site(){ SITE="${SITE:-${SITE_NAME:-}}"; [[ -n "$SITE" ]] || prompt SITE 'Site/domain'; }
admin_password(){ local choice; echo 'Administrator password:'; echo '1) Enter manually'; echo '2) Auto-generate strong password [recommended]'; [[ "$MODE" == local ]] && echo '3) Use admin for local development only'; prompt choice 'Choose' 2; case "$choice" in 1) prompt_secret ADMIN_PASSWORD 'Administrator password';; 2) ADMIN_PASSWORD="$(random_secret)";; 3) [[ "$MODE" == local ]] || die 'admin password is disabled outside local mode'; ADMIN_PASSWORD=admin;; *) die 'Invalid choice';; esac; }
db_admin(){ if sudo mariadb -e 'SELECT 1;' >/dev/null 2>&1; then DB_ADMIN=(sudo mariadb); return; fi; local u p; prompt u 'MariaDB administrator username' root; prompt_secret p 'MariaDB administrator password'; DB_ADMIN=(mariadb -u "$u" "-p$p"); "${DB_ADMIN[@]}" -e 'SELECT 1;' >/dev/null || die 'MariaDB authentication failed'; }
install_app(){ [[ -d "$BENCH_DIR/apps/$APP_NAME" ]] && { info "app already present: $APP_NAME"; return; }; local tmp; case "$APP_SOURCE_TYPE" in app-repo) bench_cmd bench get-app --branch "$APP_BRANCH" "$APP_REPO_URL";; monorepo) tmp="$(mktemp -d)"; git clone --depth 1 --branch "$APP_BRANCH" "$APP_REPO_URL" "$tmp/repo"; [[ -d "$tmp/repo/$APP_SUBDIRECTORY" ]] || die "App subdirectory not found: $APP_SUBDIRECTORY"; cp -a "$tmp/repo/$APP_SUBDIRECTORY" "$BENCH_DIR/apps/$APP_NAME"; rm -rf "$tmp";; bundled) cp -a "$SCRIPT_DIR/apps/$APP_NAME" "$BENCH_DIR/apps/$APP_NAME";; *) die "Unknown APP_SOURCE_TYPE: $APP_SOURCE_TYPE";; esac; bench_cmd ./env/bin/pip install -e "apps/$APP_NAME"; }
new_site(){ resolve_site; site_exists "$SITE" && die "Site already exists: $SITE"; admin_password; db_admin; local dbname dbuser dbpass secret note url; dbname="frappe_$(printf '%s' "$SITE" | sha256sum | cut -c1-12)"; dbuser="$dbname"; dbpass="$(random_secret)"; "${DB_ADMIN[@]}" -e "CREATE DATABASE IF NOT EXISTS \`$dbname\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; CREATE USER IF NOT EXISTS '$dbuser'@'localhost' IDENTIFIED BY '$dbpass'; GRANT ALL PRIVILEGES ON \`$dbname\`.* TO '$dbuser'@'localhost'; FLUSH PRIVILEGES;"; bench_cmd bench new-site "$SITE" --db-name "$dbname" --db-password "$dbpass" --admin-password "$ADMIN_PASSWORD" --no-mariadb-socket; install_app; bench_cmd bench --site "$SITE" install-app "$APP_NAME"; bench_cmd bench --site "$SITE" migrate; [[ "$MODE" == local ]] && { grep -qE "(^|[[:space:]])$SITE([[:space:]]|$)" /etc/hosts || echo "127.0.0.1 $SITE" | sudo tee -a /etc/hosts >/dev/null; }; url="http://$SITE:8000"; [[ "$MODE" != local ]] && url="https://$SITE"; secret="$(site_secret_file "$SITE")"; write_secret_file "$secret" SITE_NAME "$SITE" ENVIRONMENT "$MODE" SITE_URL "$url" ADMIN_USER Administrator ADMIN_PASSWORD "$ADMIN_PASSWORD" DB_NAME "$dbname" DB_USER "$dbuser" DB_PASSWORD "$dbpass" APP_NAME "$APP_NAME"; note="$(create_credential_note "$SITE" "$MODE" "$ADMIN_PASSWORD" "$dbuser" "$dbpass")"; schedule_secret_cleanup "$note" 24; ok "site created: $SITE"; info "permanent secret: $secret"; info "temporary readable credentials: $note"; }
list_sites(){ find "$BENCH_DIR/sites" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep -vE '^(assets|apps.txt)$' || true; }
update_site(){ resolve_site; site_exists "$SITE" || die 'Site not found'; install_app; bench_cmd bench --site "$SITE" migrate; bench_cmd bench --site "$SITE" clear-cache; }
delete_site(){ resolve_site; site_exists "$SITE" || die 'Site not found'; read -r -p "Type DELETE $SITE to continue: " x; [[ "$x" == "DELETE $SITE" ]] || die 'Cancelled'; bench_cmd bench drop-site "$SITE" --force; rm -f "$(site_secret_file "$SITE")"; }
restore_site(){ resolve_site; local backup; prompt backup 'Backup SQL/SQL.GZ path'; [[ -f "$backup" ]] || die 'Backup file not found'; bench_cmd bench --site "$SITE" restore "$backup"; bench_cmd bench --site "$SITE" migrate; }
case "$CMD" in new) new_site;; list) list_sites;; update) update_site;; delete) delete_site;; restore) restore_site;; menu) echo 'Use: new | restore | update | delete | list';; *) die "Unknown command: $CMD";; esac
